const HERO_ART={warrior:'assets/alden.svg',ranger:'assets/lyra.svg',mage:'assets/elias.svg',cleric:'assets/mira.svg'};
const HERO_STATE_ART={
 warrior:{idle:'assets/alden.svg',attack:'assets/alden-attack.svg',cast:'assets/alden-attack.svg',hit:'assets/alden-hit.svg',ko:'assets/alden-ko.svg'},
 ranger:{idle:'assets/lyra.svg',attack:'assets/lyra.svg',cast:'assets/lyra.svg',hit:'assets/lyra.svg',ko:'assets/lyra.svg'},
 mage:{idle:'assets/elias.svg',attack:'assets/elias.svg',cast:'assets/elias.svg',hit:'assets/elias.svg',ko:'assets/elias.svg'},
 cleric:{idle:'assets/mira.svg',attack:'assets/mira.svg',cast:'assets/mira.svg',hit:'assets/mira.svg',ko:'assets/mira.svg'}
};
function heroArt(h){return HERO_STATE_ART[h.role]?.[h.visualState||'idle']||HERO_ART[h.role]}const ENEMY_ART={slime:'assets/slime.svg',goblin:'assets/goblin.svg',wolf:'assets/wolf.svg',golem:'assets/golem.svg',boss:'assets/elder-wyrm.svg'};
const HEROES=[{name:"Alden",cls:"Warrior",role:"warrior",ability:"POWER STRIKE",maxHp:150,hp:150,atk:19,spd:1.15,level:1,xp:0,nextXp:60,aether:0,visualState:"idle"},{name:"Lyra",cls:"Ranger",role:"ranger",ability:"DOUBLE SHOT",maxHp:110,hp:110,atk:15,spd:.82,level:1,xp:0,nextXp:55,aether:0,visualState:"idle"},{name:"Elias",cls:"Mage",role:"mage",ability:"FIRE",maxHp:90,hp:90,atk:23,spd:1.35,level:1,xp:0,nextXp:58,aether:0,visualState:"idle"},{name:"Mira",cls:"Cleric",role:"cleric",ability:"CURE",maxHp:105,hp:105,atk:11,spd:1.5,level:1,xp:0,nextXp:52,aether:0,visualState:"idle"}];
const WAVES=[[["Forest Slime","slime",58,7,8]],[["Forest Wolf","wolf",72,8,9],["Forest Slime","slime",55,7,7]],[["Goblin Scout","goblin",82,9,11],["Forest Wolf","wolf",70,8,9]],[["Goblin","goblin",90,10,12],["Goblin","goblin",90,10,12],["Wolf","wolf",75,9,10]],[["Moss Golem","golem",175,13,24],["Forest Slime","slime",65,8,8]],[["Forest Imp","goblin",110,14,17],["Dark Wolf","wolf",105,13,15],["Dark Wolf","wolf",105,13,15]],[["Moss Golem","golem",210,16,27],["Goblin Guard","goblin",130,15,20]],[["Dark Wolf","wolf",145,18,23],["Dark Wolf","wolf",145,18,23],["Goblin Guard","goblin",145,17,22]],[["Goblin Captain","goblin",260,21,42],["Moss Golem","golem",190,18,31]],[["ELDER WYRM","boss",720,28,140]]];
let state={stage:1,gold:0,paused:false,enemies:[],heroTimers:[0,0,0,0],enemyTimer:0,ended:false,animating:false};
const $=id=>document.getElementById(id),wait=ms=>new Promise(r=>setTimeout(r,ms));const aliveEnemies=()=>state.enemies.filter(e=>e.hp>0);const target=()=>aliveEnemies()[0];
function makeWave(){state.enemies=WAVES[state.stage-1].map((e,i)=>({name:e[0],type:e[1],maxHp:e[2],hp:e[2],atk:e[3],gold:e[4],id:i}));render()}
function render(){let t=target();$("stage").textContent=state.stage+" / 10";$("gold").textContent=state.gold;$("enemyField").innerHTML=state.enemies.map((e,i)=>'<div id="enemy'+i+'" class="enemy-unit '+e.type+' '+(e.hp<=0?'dead ':'')+(t===e?'target':'')+'" style="'+(e.hp<=0?'display:none':'')+'"><div class="enemy-sprite"><img class="enemy-art" src="'+ENEMY_ART[e.type]+'" alt="'+e.name+'"></div><div class="enemy-mini"><b>'+e.name+'</b><div class="bar"><i style="width:'+Math.max(0,e.hp/e.maxHp*100)+'%"></i></div><small>'+Math.max(0,Math.ceil(e.hp))+' HP</small></div></div>').join("");
$("partyField").innerHTML=HEROES.map((h,i)=>'<div class="hero-sprite '+h.role+' '+(h.hp<=0?'dead':'')+'" id="sprite'+i+'"><img class="hero-art" src="'+heroArt(h)+'" alt="'+h.name+'"><label>'+h.name+'</label></div>').join("");
$("aetherPanel").innerHTML=HEROES.map((h,i)=>'<button class="aether-btn '+(h.aether>=100&&h.hp>0?'ready':'')+'" data-i="'+i+'" '+(h.aether<100||h.hp<=0||state.ended?'disabled':'')+'><span class="charge" style="width:'+h.aether+'%"></span><b>'+h.name+' · '+h.ability+'</b><small>AETHER '+Math.floor(h.aether)+'%</small></button>').join("");document.querySelectorAll(".aether-btn").forEach(b=>b.onclick=()=>useAether(+b.dataset.i));
$("partyPanel").innerHTML=HEROES.map(h=>'<div class="card"><img class="portrait" src="'+HERO_ART[h.role]+'" alt=""><div class="card-data"><div class="card-top"><b>'+h.name+'</b><b>LV '+h.level+'</b></div><div class="class">'+h.cls+'</div><div class="stats">HP '+Math.ceil(h.hp)+' / '+h.maxHp+'</div><div class="hpbar"><i style="width:'+Math.max(0,h.hp/h.maxHp*100)+'%"></i></div><div class="stats xp">XP '+h.xp+' / '+h.nextXp+'</div></div></div>').join("")}
function log(x){$("battleLog").textContent=x}function gain(h,n){h.aether=Math.min(100,h.aether+n)}
function battleFx(type,heroIndex=0){let d=document.createElement("div");d.className="battle-fx "+type+" fx-hero-"+heroIndex;d.innerHTML=type==="slash"?"╱":type==="arrow"?"➶":type==="fire"?"✦":type==="heal"?"✚":"✧";$("fxLayer").appendChild(d);setTimeout(()=>d.remove(),650)}
function floatNum(n,hero=false){let d=document.createElement("div");d.className="damage"+(hero?" hero-dmg":"");d.textContent=n;$("fxLayer").appendChild(d);setTimeout(()=>d.remove(),750)}function spell(x,heal=false){let d=document.createElement("div");d.className="spellfx"+(heal?" healfx":"");d.textContent=x;$("fxLayer").appendChild(d);setTimeout(()=>d.remove(),700)}
async function heroAttack(i){let h=HEROES[i],e=target();if(state.animating||!e||h.hp<=0)return;state.animating=true;setHeroState(i,"attack",520);$("sprite"+i)?.classList.add("attack");await wait(150);battleFx(i===0?"slash":i===1?"arrow":i===2?"arcane":"holy",i);await wait(35);let crit=Math.random()<.12,d=Math.floor(h.atk*(.85+Math.random()*.3)*(crit?1.8:1));e.hp-=d;gain(h,13);$("enemy"+e.id)?.classList.add("hit");floatNum(d);log(h.name+" attacks "+e.name+" for "+d+(crit?" — CRITICAL!":""));await wait(220);state.animating=false;if(!aliveEnemies().length)victory();else render()}
async function enemyAttack(){if(state.animating)return;let es=aliveEnemies(),alive=HEROES.map((h,i)=>h.hp>0?i:null).filter(i=>i!==null);if(!es.length||!alive.length)return;state.animating=true;let e=es[Math.floor(Math.random()*es.length)],i=alive[Math.floor(Math.random()*alive.length)],h=HEROES[i];$("enemy"+e.id)?.classList.add("lunge");await wait(165);battleFx(e.type==="wolf"?"claw":e.type==="boss"?"fire":"enemy-slash");await wait(25);let d=Math.floor(e.atk*(.8+Math.random()*.4));h.hp=Math.max(0,h.hp-d);gain(h,8);$("sprite"+i)?.classList.add("hit");setHeroState(i,h.hp>0?"hit":"ko",h.hp>0?300:0);floatNum(d,true);log(e.name+" strikes "+h.name+" for "+d+"!");await wait(250);state.animating=false;if(HEROES.every(x=>x.hp<=0))defeat();else render()}
async function useAether(i){let h=HEROES[i],e=target();if(state.animating||h.aether<100||h.hp<=0||state.paused||state.ended||!e)return;state.animating=true;h.aether=0;$("sprite"+i)?.classList.add(i>=2?"cast":"attack");await wait(160);battleFx(i===0?"power":i===1?"double-arrow":i===2?"fire":"heal",i);await wait(20);if(i===0){let d=Math.floor(h.atk*3.2);e.hp-=d;spell("✦");floatNum(d);log("Alden uses POWER STRIKE on "+e.name+"! "+d+" damage.")}if(i===1){let d=Math.floor(h.atk*3.3);e.hp-=d;spell("➶➶");floatNum(d);log("Lyra fires DOUBLE SHOT! "+d+" damage.")}if(i===2){let d=Math.floor(h.atk*3.7);e.hp-=d;spell("🔥");floatNum(d);log("Elias casts FIRE on "+e.name+"! "+d+" damage.")}if(i===3){let t=HEROES.filter(x=>x.hp>0).sort((a,b)=>a.hp/a.maxHp-b.hp/b.maxHp)[0]||h,heal=Math.floor(h.maxHp*.75+h.atk*2);t.hp=Math.min(t.maxHp,t.hp+heal);spell("✚",true);log("Mira casts CURE! "+t.name+" recovers "+heal+" HP.")}await wait(420);state.animating=false;if(!aliveEnemies().length)victory();else render()}
function victory(){let reward=state.enemies.reduce((s,e)=>s+e.gold,0);state.gold+=reward;HEROES.forEach(h=>{if(h.hp>0){h.xp+=Math.floor(18+state.stage*6);gain(h,15);while(h.xp>=h.nextXp){h.xp-=h.nextXp;h.level++;h.nextXp=Math.floor(h.nextXp*1.28);h.maxHp+=12;h.hp=h.maxHp;h.atk+=3}}});if(state.stage===10){state.ended=true;render();log("VICTORY! The Elder Wyrm falls. Forest Ruins cleared!");return}log("Wave cleared! +"+reward+" gold. Moving deeper into the ruins...");state.paused=true;render();setTimeout(()=>{state.stage++;HEROES.forEach(h=>h.hp=Math.min(h.maxHp,h.hp+Math.floor(h.maxHp*.18)));state.heroTimers=[0,0,0,0];state.enemyTimer=0;makeWave();state.paused=false;log("Wave "+state.stage+" begins!")},900)}
function defeat(){state.paused=true;render();log("The party falls... regrouping.");setTimeout(()=>{HEROES.forEach(h=>{h.hp=h.maxHp;gain(h,25)});makeWave();state.heroTimers=[0,0,0,0];state.enemyTimer=0;state.paused=false},1800)}
function reset(){HEROES.forEach((h,i)=>{let b=[[150,19,60],[110,15,55],[90,23,58],[105,11,52]][i];h.maxHp=h.hp=b[0];h.atk=b[1];h.level=1;h.xp=0;h.nextXp=b[2];h.aether=0});state={stage:1,gold:0,paused:false,enemies:[],heroTimers:[0,0,0,0],enemyTimer:0,ended:false,animating:false};makeWave();log("A new adventure begins...")}
$("pauseBtn").onclick=()=>{state.paused=!state.paused;$("pauseBtn").textContent=state.paused?"▶ RESUME":"Ⅱ PAUSE";log(state.paused?"Battle paused.":"Auto battle resumed.")};$("resetBtn").onclick=()=>{if(confirm("Reset Echoes of Aether?"))reset()};
let last=performance.now();function loop(now){let dt=Math.min((now-last)/1000,.1);last=now;if(!state.paused&&!state.ended&&aliveEnemies().length&&!state.animating){for(let i=0;i<HEROES.length;i++){let h=HEROES[i];if(h.hp>0){state.heroTimers[i]+=dt;if(state.heroTimers[i]>=h.spd){state.heroTimers[i]=0;heroAttack(i);break}}}state.enemyTimer+=dt;if(state.enemyTimer>=1.75&&!state.animating){state.enemyTimer=0;enemyAttack()}}requestAnimationFrame(loop)}makeWave();requestAnimationFrame(loop);